import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

const BASE_TEMPLATE_TEXT = [
  'NYAYANEXUS INCIDENT TEMPLATE',
  '',
  '1. Basic Report Identity',
  '- Jurisdiction:',
  '- Authority Desk:',
  '- Reference Year:',
  '- Report ID:',
  '- Filed On:',
  '',
  '2. Incident Facts',
  '- Incident Date:',
  '- Incident Time:',
  '- Incident Location:',
  '- Summary of events:',
  '',
  '3. Reporter Information',
  '- Reporter Name:',
  '- Guardian / Contact Person:',
  '- Date of Birth:',
  '- Citizenship:',
  '- Occupation:',
  '- Contact Address:',
  '',
  '4. Notes',
  '- Witnesses:',
  '- Evidence references:',
  '- Follow-up actions:',
  '',
  'Generated by NyayaNexus Studio',
].join('\n');

const resolveFilePath = (): string => {
  return FileSystem.cacheDirectory ?? FileSystem.documentDirectory ?? '';
};

const IncidentTemplateScreen: React.FC = () => {
  const [isPreparing, setIsPreparing] = useState<boolean>(false);

  const handleTemplateExport = async (): Promise<void> => {
    setIsPreparing(true);

    try {
      const basePath = resolveFilePath();
      if (!basePath) {
        Alert.alert('Storage Unavailable', 'Could not access local storage to generate the template.');
        return;
      }

      const fileUri = `${basePath}NyayaNexus-Incident-Template.txt`;
      await FileSystem.writeAsStringAsync(fileUri, BASE_TEMPLATE_TEXT, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri);
      } else {
        Alert.alert('Template Ready', 'Incident template generated in local storage.');
      }
    } catch {
      Alert.alert('Export Failed', 'Unable to generate incident template right now.');
    } finally {
      setIsPreparing(false);
    }
  };

  return (
    <View style={styles.container}>
      <LinearGradient colors={['#0A0F1D', '#17345E', '#0B4A6F']} style={styles.hero}>
        <View style={styles.iconWrap}>
          <Ionicons name="document-text" size={24} color="#05111F" />
        </View>
        <Text style={styles.title}>Base Incident Template</Text>
        <Text style={styles.subtitle}>
          Generate a clean editable template for intake and reporting workflows without external dependencies.
        </Text>
      </LinearGradient>

      <TouchableOpacity style={styles.button} onPress={handleTemplateExport} disabled={isPreparing}>
        <Ionicons name={isPreparing ? 'sync' : 'document-attach'} size={18} color="#05111F" />
        <Text style={styles.buttonText}>{isPreparing ? 'Preparing Template...' : 'Export Template File'}</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050A18',
    gap: 14,
    padding: 20,
  },
  hero: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#26486D',
    gap: 8,
    padding: 20,
  },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#7DF9FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#EAF4FF',
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: '#A8C0DD',
    fontSize: 14,
    lineHeight: 20,
  },
  button: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: '#7DF9FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  buttonText: {
    color: '#05111F',
    fontSize: 14,
    fontWeight: '800',
  },
});

export default IncidentTemplateScreen;
