import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {
  StudioHeaderBanner,
  TemplateDownloadCard,
  ReportIdentityCard,
  IncidentInfoCard,
  ReporterInfoCard,
  ActionFormButton,
} from '../uiBlocks/IncidentStudio/exports';

interface IncidentFormState {
  jurisdiction: string;
  authorityDesk: string;
  referenceYear: string;
  reportId: string;
  filedOn: string;
  incidentDate: string;
  incidentTime: string;
  incidentLocation: string;
  reporterName: string;
  guardianName: string;
  dateOfBirth: string;
  citizenship: string;
  occupation: string;
  contactAddress: string;
}

const createInitialFormState = (): IncidentFormState => ({
  jurisdiction: '',
  authorityDesk: '',
  referenceYear: '',
  reportId: '',
  filedOn: '',
  incidentDate: '',
  incidentTime: '',
  incidentLocation: '',
  reporterName: '',
  guardianName: '',
  dateOfBirth: '',
  citizenship: '',
  occupation: '',
  contactAddress: '',
});

const requiredFields: Array<{ field: keyof IncidentFormState; label: string }> = [
  { field: 'jurisdiction', label: 'Jurisdiction' },
  { field: 'authorityDesk', label: 'Authority Desk' },
  { field: 'reportId', label: 'Report ID' },
  { field: 'incidentLocation', label: 'Incident Location' },
  { field: 'reporterName', label: 'Reporter Name' },
];

const escapeHtml = (value: string): string => {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};

const row = (label: string, value: string): string => {
  const safeValue = escapeHtml(value.trim() || '-');
  return `<p class="row"><span class="label">${label}:</span><span class="value">${safeValue}</span></p>`;
};

const createIncidentHtml = (form: IncidentFormState): string => `
  <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; padding: 18px; line-height: 1.55; color: #111827; }
        h1 { text-align: center; color: #0F3A67; margin: 0 0 6px; }
        h2 { color: #0F3A67; border-bottom: 1px solid #E5E7EB; padding-bottom: 4px; margin-bottom: 8px; }
        .meta { text-align: center; color: #4B5563; margin: 0 0 18px; font-size: 12px; }
        .section { margin-bottom: 18px; }
        .row { margin: 7px 0; }
        .label { font-weight: bold; display: inline-block; width: 180px; color: #1F2937; }
        .value { color: #111827; }
      </style>
    </head>
    <body>
      <h1>Incident Intake Report</h1>
      <p class="meta">Generated via Gemini-Powered-Law-Guidance</p>

      <div class="section">
        <h2>Identity</h2>
        ${row('Jurisdiction', form.jurisdiction)}
        ${row('Authority Desk', form.authorityDesk)}
        ${row('Reference Year', form.referenceYear)}
        ${row('Report ID', form.reportId)}
        ${row('Filed On', form.filedOn)}
      </div>

      <div class="section">
        <h2>Incident Facts</h2>
        ${row('Incident Date', form.incidentDate)}
        ${row('Incident Time', form.incidentTime)}
        ${row('Incident Location', form.incidentLocation)}
      </div>

      <div class="section">
        <h2>Reporter Profile</h2>
        ${row('Reporter Name', form.reporterName)}
        ${row('Guardian / Contact Person', form.guardianName)}
        ${row('Date of Birth', form.dateOfBirth)}
        ${row('Citizenship', form.citizenship)}
        ${row('Occupation', form.occupation)}
        ${row('Contact Address', form.contactAddress)}
      </div>
    </body>
  </html>
`;

const createTemplateHtml = (): string => `
  <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; padding: 18px; line-height: 1.6; color: #111827; }
        h1 { text-align: center; color: #0F3A67; margin: 0 0 6px; }
        .meta { text-align: center; color: #4B5563; margin: 0 0 16px; font-size: 12px; }
        h2 { color: #0F3A67; border-bottom: 1px solid #E5E7EB; padding-bottom: 4px; margin-bottom: 8px; }
        .line { margin: 8px 0; }
      </style>
    </head>
    <body>
      <h1>Incident Intake Template</h1>
      <p class="meta">Blank reference sheet generated by Gemini-Powered-Law-Guidance</p>

      <h2>Identity</h2>
      <p class="line">Jurisdiction: ________________________________</p>
      <p class="line">Authority Desk: _____________________________</p>
      <p class="line">Reference Year: _____________________________</p>
      <p class="line">Report ID: __________________________________</p>
      <p class="line">Filed On: ____________________________________</p>

      <h2>Incident Facts</h2>
      <p class="line">Incident Date: ______________________________</p>
      <p class="line">Incident Time: ______________________________</p>
      <p class="line">Incident Location: ___________________________</p>
      <p class="line">Summary: ____________________________________</p>

      <h2>Reporter Profile</h2>
      <p class="line">Reporter Name: ______________________________</p>
      <p class="line">Guardian / Contact: _________________________</p>
      <p class="line">Date of Birth: ______________________________</p>
      <p class="line">Citizenship: _________________________________</p>
      <p class="line">Occupation: _________________________________</p>
      <p class="line">Contact Address: ____________________________</p>
    </body>
  </html>
`;

const IncidentReportStudioScreen: React.FC = () => {
  const [form, setForm] = useState<IncidentFormState>(createInitialFormState);
  const [downloadingTemplate, setDownloadingTemplate] = useState<boolean>(false);
  const [exportingPdf, setExportingPdf] = useState<boolean>(false);

  const updateField = (fieldName: keyof IncidentFormState, value: string): void => {
    setForm((current) => ({
      ...current,
      [fieldName]: value,
    }));
  };

  const validateRequiredFields = (): boolean => {
    for (const item of requiredFields) {
      if (!String(form[item.field]).trim()) {
        Alert.alert('Validation Error', `Please fill the ${item.label} field.`);
        return false;
      }
    }

    return true;
  };

  const exportTemplatePdf = async (): Promise<void> => {
    setDownloadingTemplate(true);

    try {
      const printable = await Print.printToFileAsync({
        html: createTemplateHtml(),
      });

      if (!printable?.uri) {
        Alert.alert('Error', 'Failed to prepare template PDF.');
        return;
      }

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(printable.uri);
      } else {
        Alert.alert('Template Ready', 'Template PDF generated successfully.');
      }
    } catch {
      Alert.alert('Template Error', 'Unable to export incident template right now.');
    } finally {
      setDownloadingTemplate(false);
    }
  };

  const exportPdf = async (): Promise<void> => {
    if (!validateRequiredFields()) {
      return;
    }

    setExportingPdf(true);

    try {
      const printable = await Print.printToFileAsync({
        html: createIncidentHtml(form),
      });

      if (!printable?.uri) {
        Alert.alert('Error', 'Failed to generate PDF.');
        return;
      }

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(printable.uri);
      } else {
        Alert.alert('PDF Generated', 'Incident report generated successfully.');
      }
    } catch {
      Alert.alert('Error', 'Failed to generate PDF.');
    } finally {
      setExportingPdf(false);
    }
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <StudioHeaderBanner
        title="Incident Studio"
        subtitle="Prepare intake details, review fields, and export a printable report in one flow"
      />

      <View style={styles.stepCard}>
        <Text style={styles.stepText}>Step 1: Export blank template</Text>
        <Text style={styles.stepText}>Step 2: Fill incident details</Text>
        <Text style={styles.stepText}>Step 3: Generate final PDF</Text>
      </View>

      <TemplateDownloadCard isDownloading={downloadingTemplate} onDownload={exportTemplatePdf} />

      <View style={styles.formCard}>
        <Text style={styles.formTitle}>Create Incident Report</Text>
        <Text style={styles.formSubtitle}>
          Fill the required sections below and generate a structured document for sharing or filing.
        </Text>

        <ReportIdentityCard
          formData={{
            jurisdiction: form.jurisdiction,
            authorityDesk: form.authorityDesk,
            referenceYear: form.referenceYear,
            reportId: form.reportId,
            filedOn: form.filedOn,
          }}
          onChange={updateField}
        />

        <IncidentInfoCard
          formData={{
            incidentDate: form.incidentDate,
            incidentTime: form.incidentTime,
            incidentLocation: form.incidentLocation,
          }}
          onChange={updateField}
        />

        <ReporterInfoCard
          formData={{
            reporterName: form.reporterName,
            guardianName: form.guardianName,
            dateOfBirth: form.dateOfBirth,
            citizenship: form.citizenship,
            occupation: form.occupation,
            contactAddress: form.contactAddress,
          }}
          onChange={updateField}
        />

        <ActionFormButton
          title="Generate Incident PDF"
          loadingTitle="Generating PDF..."
          isLoading={exportingPdf}
          onPress={exportPdf}
          iconName="document"
          backgroundColor="#7DF9FF"
        />
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050A18',
  },
  stepCard: {
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#25466D',
    backgroundColor: '#0D1B31',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  stepText: {
    color: '#F6A720',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  formCard: {
    margin: 20,
    marginTop: 0,
    marginBottom: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#20385C',
    backgroundColor: '#0C1427',
    padding: 14,
  },
  formTitle: {
    color: '#EAF3FF',
    fontSize: 21,
    fontWeight: '800',
  },
  formSubtitle: {
    marginTop: 5,
    marginBottom: 12,
    color: '#9FB4D1',
    fontSize: 13,
    lineHeight: 19,
  },
});

export default IncidentReportStudioScreen;

